linters:
  # Please, do not use `enable-all`: it's deprecated and will be removed soon.
  # Inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint.
  # Full list of linters - https://golangci-lint.run/usage/linters
  disable-all: true
  enable:
    - errcheck # Mandatory. Do not disable.
    - ineffassign # Mandatory. Do not disable.
    - staticcheck # Mandatory. Do not disable.
    - bodyclose # https://github.com/timakin/bodyclose
    - gomodguard
    - nolintlint

# TODO:
#    - gosec
#    - gocritic
#    - goimports
#    - gosimple
#    - govet
#    - noctx
#    - stylecheck
#    - typecheck
#    - unused

linters-settings:
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style

  errcheck:
    # List of functions to exclude from checking, where each entry is a single function to exclude.
    # See https://github.com/kisielk/errcheck#excluding-functions for details.
    exclude-functions:
      - (io.Closer).Close
      - (io.ReadCloser).Close

  govet:
    enable-all: true
    disable:
     - shadow
     - fieldalignment

  gomodguard:
    blocked:
      # List of blocked modules.
      modules:
        - github.com/pkg/errors:
            recommendations:
              - github.com/mailgun/errors
              - errors
            reason: "Deprecated"

  stylecheck:
    # https://staticcheck.io/docs/options#checks
    checks: ["all"]

issues:
  # Which files to exclude: they will be analyzed, but issues from them won't be reported.
  # There is no need to include all autogenerated files,
  # we confidently recognize autogenerated files.
  # If it's not, please let us know.
  # "/" will be replaced by current OS file path separator to properly work on Windows.
  # Default: []
  exclude-files:
    - "^mock_*"

  # Maximum issues count per one linter. Set to 0 to disable. Default is 50.
  max-issues-per-linter: 0

  # Maximum count of issues with the same text. Set to 0 to disable. Default is 3.
  max-same-issues: 50

run:
  # include test files or not, default is true
  # TODO(DE-1139): Enable
  tests: false

  # Timeout for analysis, e.g. 30s, 5m.
  # Default: 1m
  timeout: 5m
