name: CI

on:
  pull_request:
  push:
    branches: [ main ]

# Cancels any in-flight actions if the PR is updated before jobs complete.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.26.x

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true # caching and restoring go modules and build outputs

      - name: Install deps
        run: go mod download

      - name: nilaway
        run: make nilaway

      # TODO(vtopc): use golangci/golangci-lint-action instead:
      - name: lint
        run: make lint
