name: Update CHANGELOG from GitHub Release

on:
  # all vars - https://github.com/dhimmel/dump-actions-context/blob/main/contexts/release.json
  release:
    types: [published]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Update CHANGELOG
        uses: actions/github-script@v9
        with:
          # TODO(vtopc): update `const Version` in version.go file too.
          script: |
            const fs = require('fs');

            const release = context.payload.release;
            const tag = release.tag_name;
            const title = tag.replace(/^v/, '');
            const date = release.published_at.substring(0, 10);
            const body = (release.body || 'No release notes provided.')
              .replace(/\r\n/g, '\n')
              .replace(/^## What's Changed/gm, "#### Changed")
              .trim();

            const changelogPath = 'CHANGELOG.md';

            const newEntry = `### [${title}] - ${date}\n${body}\n\n`;

            console.log('----- NEW CHANGELOG ENTRY START -----');
            console.log(newEntry);
            console.log('----- NEW CHANGELOG ENTRY END -----');

            let changelog = '';
            if (fs.existsSync(changelogPath)) {
              changelog = fs.readFileSync(changelogPath, 'utf8');
            } else {
              changelog = '# Changelog\n\nAll notable changes to this project will be documented in this file.\n';
            }

            // Insert after the first header
            const updated = changelog.replace(
            /(##[^\n]*\n)/,
            `$1${newEntry}`
            );

            fs.writeFileSync(changelogPath, updated);

      - name: Create PR
        # Requires "Allow GitHub Actions to create and approve pull requests" to be enabled in the repository settings
        uses: peter-evans/create-pull-request@v8.1.1
        with:
          base: ${{ github.event.repository.default_branch }}
          commit-message: "Update CHANGELOG.md for ${{ github.event.release.name || github.event.release.tag_name }}"
          branch: gha/update-changelog-${{ github.event.release.id }}
          delete-branch: true
          title: Update CHANGELOG.md for ${{ github.event.release.name || github.event.release.tag_name }}
          assignees: ${{ github.event.release.author.login }}
          body: |
            Update CHANGELOG.md for ${{ github.event.release.name }} (${{ github.event.release.tag_name }}).
